local theme = table.clone(require(script.Parent.Breeze))
theme.Accent = Color3.fromRGB(34, 132, 226); theme.Background = Color3.fromRGB(224, 235, 244)
theme.Surface = Color3.fromRGB(249, 252, 255); theme.SurfaceSecondary = Color3.fromRGB(235, 242, 248)
theme.Text = Color3.fromRGB(29, 43, 56); theme.MutedText = Color3.fromRGB(92, 110, 126)
theme.Stroke = Color3.fromRGB(172, 191, 207); theme.Transparency = 0.04
return theme
